openshift/containernetworking-plugins

build_linux.sh

per https://jira.coreos.com/browse/ART-666 (for FIPS enablement)

build_linux.sh: remove no_openssl

---

Dockerfile

According to @squeed :
> We're seeing occasional situations where our binaries coredump repeatedly - this is tracked in 1725832.
This exports `CGO_ENABLED=0` before we run the build script.

Bug 1752008: Adds ENV CGO_ENABLED=0 to disable building with cgo

---

plugins/main/loopback/loopback.go
plugins/main/loopback/loopback_test.go

There is a bug in CRIO that issues deletes against processes running in the root network namespace. This means we take the node's loopback interface down. This is bad.
This bug was always present, BTW, but we skipped loopback on teardown.
/cc @dcbw

Bug 1754638: loopback: don't tear down

---

plugins/main/loopback/loopback.go
plugins/main/loopback/loopback_test.go

There is a bug in CRIO that issues deletes against processes running in
the root network namespace. This means we take the node's loopback
interface down. This is bad.
This bug was always present, BTW, but we skipped loopback on teardown.

Bug 1754154: loopback: don't tear down

---

Dockerfile
build_linux.sh

This reverts #18  which set `CGO_ENABLED=1` and no_openssl tag

Revert CGO enabled / no_openssl tag

---

plugins/ipam/static/README.md
plugins/ipam/static/main.go
plugins/ipam/static/static_test.go
plugins/meta/tuning/README.md
plugins/meta/tuning/tuning.go
plugins/meta/tuning/tuning_test.go

Contains three commits for:
* introduces new capability flag to change MAC address and to specify IP addresses by tuning and static
* Support "args" field in JSON config to additional configuration in static and tuning plugins.
* introduce priorities for IPs input among CNI_ARGS, 'args' and runtimeConfig

Static IPAM plugin updates

---

pkg/ip/link_linux.go
plugins/main/bridge/bridge.go

The interface plugins should have absolute control over their addressing
and routing.
Signed-off-by: Casey Callendrello <cdc@redhat.com>

Bug 1837209: ptp, bridge: disable accept_ra on the host-side interface

---

plugins/ipam/dhcp/daemon.go
plugins/ipam/dhcp/lease.go

Signed-off-by: Aneesh Puttur <aneeshputtur@gmail.com>

Bug 1818786: Fix handling of delay in acquiring lease with stp turned on

---

Dockerfile

Add building of Windows plugin binaries into the image. These binaries will be used by the [Windows Machine Config Operator](https://github.com/openshift/windows-machine-config-operator/) as part of preparing a VM to become an OpenShift worker node.
Signed-off-by: Aravindh Puthiyaparambil <aravindh@redhat.com>

Dockerfile: build Windows plugins

---

build_windows.sh

This fixes multi-arch builds of this container image after 
https://github.com/openshift/containernetworking-plugins/pull/30 .

Fix build of Windows binaries when run on other architectures

---

Dockerfile

Updating ose-containernetworking-plugins builder & base images to be consistent with ART
Reconciling with https://github.com/openshift/ocp-build-data/tree/990044f295fb1d5e238823902962dbcfa1c041c9/images/ose-containernetworking-plugins.yml
If you have any questions about this pull request, please reach out to `@art-team` in the `#aos-art` coreos slack channel.

Bug 1878163: Updating ose-containernetworking-plugins builder & base images to be consistent with ART

---

plugins/main/ipvlan/README.md
plugins/main/ipvlan/ipvlan.go
plugins/main/ipvlan/ipvlan_test.go

This change makes ipvlan master parameter optional.
Default to default route interface as macvlan does.
Signed-off-by: Tomofumi Hayashi <tohayash@redhat.com>

Bug 1879244: ipvlan - make master config as optional

---

Dockerfile

Updating ose-containernetworking-plugins builder & base images to be consistent with ART
Reconciling with https://github.com/openshift/ocp-build-data/tree/f66c03011773dc3755ad874fc691be612914d65f/images/ose-containernetworking-plugins.yml
If you have any questions about this pull request, please reach out to `@art-team` in the `#aos-art` coreos slack channel.
Depends on https://github.com/openshift/images/pull/44 . Allow it to merge and then run `/test all` on this PR.

Updating ose-containernetworking-plugins builder & base images to be consistent with ART

---

plugins/meta/vrf/README.md
plugins/meta/vrf/main.go
plugins/meta/vrf/vrf.go
plugins/meta/vrf/vrf_test.go

This includes:
- more tests
- an optional tableid parameter
- making the cni compatible to 0.3.1

Re-align with upstream VRF changes

---

plugins/main/host-device/host-device.go

This commit would make host-device plugin as a placeholder
for DPDK device when applications wants to attach it with
a pod container through network attachment definition.
Merges changes from https://github.com/containernetworking/plugins/pull/490

Bug 1989342: host-device: Add support for DPDK device

---

plugins/meta/tuning/tuning.go
plugins/meta/tuning/tuning_test.go

Signed-off-by: mmirecki <mmirecki@redhat.com>
d/s merge of:
https://github.com/containernetworking/plugins/pull/730
The tuning-cni config currently allows to specif duplicated sysctls, also with conflicting values. Duplicated sysctl entries are usually not used intentionally, but are rather the result of an error in configuration.
This PR adds a check for duplicated sysctl's.

Check for duplicated sysctl keys

---

plugins/meta/tuning/tuning.go

Which causes a regression related to https://issues.redhat.com/browse/OCPBUGS-5289
This reverts commit 198ab129a153dd9077d3f78d2eb3ee7d1ab72b0f.

OCPBUGS-5292: Revert "Fix path substitution to enable setting sysctls on vlan interfaces" (ocp 4.13)

---

Dockerfile

Now that the binary is being dynamically compiled downstream, the binary must match the RHEL version of RHCOS because it is copied to the host.

Add rhel9 binary

---

plugins/main/bridge/bridge.go
plugins/main/bridge/bridge_test.go

Following https://issues.redhat.com/browse/CNV-28040, this PR cherry-picks https://github.com/containernetworking/plugins/pull/997

OCPBUGS-29888: cherry-pick containernetworking/plugins#997

---

plugins/main/bridge/bridge.go
plugins/main/bridge/bridge_test.go

https://issues.redhat.com/browse/CNV-38720, this PR back ports  https://github.com/openshift/containernetworking-plugins/pull/154

OCPBUGS-30045: [4.15] cherry-pick containernetworking/plugins#997

---

Dockerfile
Dockerfile.microshift

Similar to https://github.com/openshift/egress-router-cni/pull/82. Needed for OKD installs to succeed.
https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/test-platform-results/logs/periodic-ci-openshift-release-master-okd-scos-4.16-e2e-aws-ovn/1798613975458385920/artifacts/e2e-aws-ovn/gather-extra/artifacts/pods.json shows the failing containers with this error.

OKD-218: install util-linux

---

pkg/ip/addr_linux.go
pkg/ipam/ipam_linux.go

IPv6 configuration is valid if DAD does not fail

OCPBUGS-55346: Check error returned by ipv6 SettleAddresses

---

.ci-operator.yaml
Dockerfile

Related to https://issues.redhat.com/browse/ART-13434
Build passed: https://art-jenkins.apps.prod-stable-spoke1-dc-iad2.itup.redhat.com/job/aos-cd-builds/job/build%252Focp4-konflux/13732

OCPBUGS-59568: stop installing rpms that are already in the base image
